### ISSUE TITLE
Error due to caption too long

### ISSUE THREAD

**Issue by norm-git** [tomyangsh/tmdb-bot#1]
Hmmm unable to fix it myself, please if you can pay attention to this error and try to fix it.

telethon.client.updates - ERROR - Unhandled exception on tv_info
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/updates.py", line 443, in _dispatch_update
    await callback(event)
  File "/home/tmdb.py", line 208 in tv_info
await bot.send_message(chat_id, info, file=poster)
  File "/usr/local/lib/python3.8/dist-packages/telethon/tl/custom/message.py", line 686, in reply
    return await self._client.send_message(
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/messages.py", line 690, in send_message
    return await self.send_file(
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/uploads.py", line 385, in send_file
    return self._get_response_message(request, await self(request), entity)
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.MediaCaptionTooLongError: The caption is too long (caused by SendMediaRequest)

**Comment by tomyangsh** [comment]
Hi, could you tell me which TV show caused this? Please provide the name or the TMDb id so I can take a look into it.

**Comment by norm-git** [comment]
> Hi, could you tell me which TV show caused this? Please provide the name or the TMDb id so I can take a look into it.
 
I have changed 
this line
await bot.send_message(chat_id, info, file=poster)
to:
await event.reply(info, file=poster)

and I am using language IS
 `game of thrones` `ilustres Ignorantes` these are the tvshows

**Comment by tomyangsh** [comment]
I see the problem here, that non-Chinese description could take quiet more characters. And the size of image cations is far limited than the size of normal messages. A quick way to fix this is to separate the image and the caption by changing it to:
```
await bot.send_file(chat_id, poster)
await bot.send_message(chat_id, info)
```
And you might want to change the season_info part 
https://github.com/tomyangsh/tmdb-bot/blob/857063f5c10629783b69c16e4e7c151cb6a026a6/tmdb.py#L106
to make it looks simpler.

**Comment by norm-git** [comment]
> I see the problem here, that non-Chinese description could take quiet more characters. And the size of image cations is far limited than the size of normal messages. A quick way to fix this is to separate the image and the caption by changing it to:
> 
> ```
> await bot.send_file(chat_id, poster)
> await bot.send_message(chat_id, info)
> ```
> 
> And you might want to change the season_info part
> 
> https://github.com/tomyangsh/tmdb-bot/blob/857063f5c10629783b69c16e4e7c151cb6a026a6/tmdb.py#L106
> 
> 
> to make it looks simpler.

is working separate media and caption
I'll leave it like that

`await event.reply(file=poster)
await event.reply(info)
